Step4
code-squad/java-ims pull request #136
Opened 2019-01-13 16:50 UTC by Choi-dongsun

PR과 함께 몇가지 질문드립니다.

1
Mock Test 사용이 굉장히 어렵게 느껴집니다.
단위&인수테스트로 확인 가능한 상황이라고 가정할 때, 굳이 Service에서 테스트할 필요가 있을까요?

2
Label에 연결된 issue 의 수를 보여주려할 때, 
성능 개선을 위해 생성자에 countOfissue = 0 로 넣어주는 방식으로 구현이 가능할 텐데요.
소규모/대규모 서비스에 상관없이 무조건적으로 그렇게 해야할까요? 
속도의 차이가 어느정도인지 가늠이 가지 않아서 현업에선 어떻게하는지 궁금합니다.

2019-01-14 00:50 UTC, javajigi commented
@Choi-dongsun 
1. 우선순위 상으로 낮을 수 있음.
Service에서 핵심 로직을 구현하지 않고 Domain 객체가 담당하도록 구현한 후 테스트한다면 Service와 같은 객체의 Mock 테스트는 생략해도 된다고 생각함.

2. 무조건적이라는 것은 없음.
성능상 이슈가 없다면 굳이 역정규화를 하지 않아도 괜찮음.
한번에 보여줘야할 Label의 수가 많지 않다면 굳이 가지지 않아도 될 것으로 판단됨.
Label의 수가 많고, 한번에 보여주는 Label의 수가 많아진다면 고려해볼만한 요소라고 생각함.

2019-01-14 00:56 UTC, javajigi requested changes
전체적인 설계와 구현, 테스트 구현 💯 
피드백 좀 남겼어요.

2019-01-14 00:56 UTC, javajigi commented on src/main/java/codesquad/domain/Issue.java
> +        this.closed = closed;
this(0L, subject, comment, writer, deleted, closed);

위와 같이 생성자의 경우 인자가 적은 생성자가 가장 많은 생성자를 호출하는 구조로 구현할 것을 추천

2019-01-14 00:56 UTC, javajigi commented on src/main/java/codesquad/domain/Milestone.java
> +    public long getProgress() {
메소드 이름이 get보다는 다른 이름이 나을 것 같음.

2019-01-14 00:56 UTC, javajigi commented on src/main/java/codesquad/domain/Milestone.java
> +        return 300 * getOpenIssue() / (getCloseIssue() + getOpenIssue());
300이라는 숫자의 의미는?
하드코딩하지 말고 상수로 구현

2019-01-14 00:56 UTC, javajigi commented on src/main/java/codesquad/service/IssueService.java
> +        milestone.addIssue(issue);
`issue.setMilestone(milestone);` 구현을 이곳에 구현하지 말고 milestone의 addIssue() 메소드에 구현하는 것은 어떨까?

2019-01-14 00:56 UTC, javajigi commented on src/main/java/codesquad/service/LabelService.java
> +        label.update(updatedLabel);
Label 수정도 관리자 또는 생성자와 같은 사용자 체크를 해야하지 않을까?

2019-01-16 19:40 UTC, Choi-dongsun commented on src/main/java/codesquad/domain/Milestone.java
> +    public long getProgress() {
HTML 활용 위해 어쩔 수 없는 메서드명

2019-01-17 00:51 UTC, merged